### ISSUE TITLE
File from URL sticks

### ISSUE THREAD

**Issue by JMante1** [MyersResearchGroup/SeqImprove#1]
If you try and import a file from a URL then it continues to think indefinitely.

**Comment by JMante1** [comment]
I mean a synbiohub url

**Comment by Duncan-Britt** [comment]
> I mean a synbiohub url

Is this an example of the kind of url you're intending: [https://synbiohub.org/public/CnDatabase/CnD_collection/1](https://synbiohub.org/public/CnDatabase/CnD_collection/1) ? Or would it be something else? Can you give me more examples?

**Comment by JMante1** [comment]
I mean a url like this: https://synbiohub.org/public/igem/BBa_K1444010/1 (a url to a collection was never meant to work - has to go to an individual part).

**Comment by JMante1** [comment]
Yes, the urls should only come from synbiohub. Any DNA components with a sequence should work. E.g. https://synbiohub.org/public/CnDatabase/GFP/1
https://synbiohub.org/public/igem/BBa_K812010/1
