### ISSUE TITLE
Users should be able to select part libraries from SBH

### ISSUE THREAD

**Issue by Duncan-Britt** [MyersResearchGroup/SeqImprove#45]
to annotate against, and reuse them later.

**Comment by cjmyers** [comment]
Users should be able to select either the default library for SynBict annotations or be able to select a set of SynBioHub libraries to use.

**Comment by cl117** [comment]
feature_libraries: `SeqImprove/apps/server/assets/synbict/feature-libraries`
From SynBioHub -> Root Collections -> Users can select which collection to use as the library for SynBict
For SynBict [https://github.com/SD2E/SYNBICT]-> cmd line -> change the library point to SynBioHub libraries ["--featureURLs"] -> download lib -> annotate 
From SBH/rootCollections/ -> list all URLs, line#44 in `app.py`.
For this issue, we should implement the above requirement in both frontend and backend.

**Comment by cl117** [comment]
`https://synbiohub.org/rootcollections`

**Comment by cl117** [comment]
🐛 
1. Fix the main branch by commenting "fetching from Synbiohub" and redeploying the front end. Make the main branch work.
2. Download the public collection on the list; the code should only look for new collections, cache the old collection locally, and don't download collections.

**Comment by cjmyers** [comment]
Completed
