### ISSUE TITLE
Improve metadata: Add type support

### ISSUE THREAD

**Issue by Duncan-Britt** [MyersResearchGroup/SeqImprove#65]
It means let the user specify whether the component uses linear or circular DNA.

**Comment by cjmyers** [comment]
Page 23 of the SBOL 2.3 specification and Table 3.

Topology label with dropdown menu that includes:

1) Linear
2) Circular
3) Double-stranded 
4) Single-stranded
5) Linear double-stranded
6) Circular double-stranded
7) Linear single-stranded
8) Circular single-stranded
