### ISSUE TITLE
UI: Create warning if user enters invalid characters into DNA sequence

### ISSUE THREAD

**Issue by Duncan-Britt** [MyersResearchGroup/SeqImprove#66]
Add warnings into the following places,
- [x] Sequence Editor, Add error message
- [x] Upload a invalid Fasta includes DNA or protein file, upload successful + with warning message said file include invalid chars
- [x] Save or edit in the Sequence Editor -> block if invalid -> after correct it -> unblock
- [x] Upload to SynBioHub -> block (anytime when export the document, block)
- [x] Highlight the invalid characters (when click the pencil)

**Comment by cjmyers** [comment]
https://www.bioinformatics.org/sms/iupac.html
