### ISSUE TITLE
UI: Make Display ID read only outside of overview page

### ISSUE THREAD

**Issue by Duncan-Britt** [MyersResearchGroup/SeqImprove#67]
Checking or unchecking a sequence annotation while the display id is being edited will remove the unchecked sequence annotations

**Comment by cjmyers** [comment]
[ ] Remove pencil from id on top
[ ] Add id with pencil on the Overview page to allow editing of the displayId
[ ] Add name with pencil on the Overview page to allow editing of the name
[ ] Add ability to edit the description on the Overview page
