### ISSUE TITLE
SeqImprove clean download versus same download

### ISSUE THREAD

**Issue by JMante1** [MyersResearchGroup/SeqImprove#9]
Currently synbiohub files that are editted and downloaded can't be reuploaded to synbhiohub as it still has all the synbiohub prefixes. Adding an option to 'clean' all the synbiohub prefixes would be useful.

**Comment by JMante1** [comment]
Can use the clean command found here: https://github.com/BioRDM/synbio2easy

**Comment by cl117** [comment]
How to reproduce this bug: download the SBOL file from seqImprove -> upload to one collection on SBH -> edit the sequence in SeqImprove -> Download the edited SBOL file -> upload to the same collection on SBH -> 
![image](https://github.com/MyersResearchGroup/SeqImprove/assets/13355576/d92f408b-2826-4eb9-982b-3e717bfb5df4)

**Comment by cl117** [comment]
After changing the `...Test_Part/1` to `...Test_Part/2`, the new part can be uploaded as a new part. So, the issue is to use SynBio2Easy to create a new id each time for a new edited sequence.

**Comment by cl117** [comment]
Maybe use PySBOL2: https://pysbol2.readthedocs.io/en/latest/getting_started.html

**Comment by cl117** [comment]
testcase 2: change sequence -> upload -> not allowed, error: "A submission with this id already exists, and it includes an object: https://synbiohub.org/user/ryangreer/friday_test/Test_Part_seq/1 that is already in this repository and has different content"
testcase 3: change uri with "Clean" -> nothing happend
testcase 4: change the partname (<sbol:ComponentDefinition rdf:about) -> successfully upload
Conclusion: sequence or domain doesn't matter.
